export default {
    HOME:"INMOBICAPITAL",
 
    LOGIN:"INICIAR",
    SIGNUP:"REGISTRO",
    PROFILE:"MI PERFIL",
    FORMULARIOS:"COMPLETA TU REGISTRO",
    FINANCIEROS:"FINANCIEROS",
    BENEFICIARIOS:"BENEFICIARIOS",
    ADDBENE:"NUEVO BENEFICIARIO",
    CARGADOCS:"CARGAR DOCUMENTOS",
    PEP:"PEP",
    SIMULADOR:"SIMULADOR DE INVERSIONES",
    MISDATOS:"MIS DATOS",
    FORM1:"PASO 1 de 5",
    FORM2:"PASO 2 de 5",
    FORM3:"PASO 3 de 5",
    FORM4:"PASO 4 de 5",
    FORM5:"PASO 5 de 5",
    MIINVERSION:"MIS INVERSIONES",

    


}